name: IIVI
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - _tflow_select=2.1.0=gpu
  - absl-py=0.13.0=py37h06a4308_0
  - aiohttp=3.7.4=py37h27cfd23_1
  - astor=0.8.1=py37h06a4308_0
  - astunparse=1.6.3=py_0
  - async-timeout=3.0.1=py37h06a4308_0
  - attrs=21.2.0=pyhd3eb1b0_0
  - blas=1.0=mkl
  - blinker=1.4=py37h06a4308_0
  - brotlipy=0.7.0=py37h27cfd23_1003
  - c-ares=1.17.1=h27cfd23_0
  - ca-certificates=2021.7.5=h06a4308_1
  - cachetools=4.2.2=pyhd3eb1b0_0
  - certifi=2021.5.30=py37h06a4308_0
  - cffi=1.14.6=py37h400218f_0
  - chardet=3.0.4=py37h06a4308_1003
  - click=8.0.1=pyhd3eb1b0_0
  - coverage=5.5=py37h27cfd23_2
  - cryptography=3.4.7=py37hd23ed53_0
  - cudatoolkit=10.1.243=h6bb024c_0
  - cudnn=7.6.5=cuda10.1_0
  - cupti=10.1.168=0
  - cython=0.29.24=py37h295c915_0
  - gast=0.4.0=py_0
  - google-auth=1.33.0=pyhd3eb1b0_0
  - google-auth-oauthlib=0.4.1=py_2
  - google-pasta=0.2.0=py_0
  - grpcio=1.36.1=py37h2157cd5_1
  - h5py=2.10.0=py37hd6299e0_1
  - hdf5=1.10.6=hb1b8bf9_0
  - idna=2.10=pyhd3eb1b0_0
  - importlib-metadata=3.10.0=py37h06a4308_0
  - intel-openmp=2021.3.0=h06a4308_3350
  - keras-preprocessing=1.1.2=pyhd3eb1b0_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgfortran-ng=7.5.0=ha8ba4b0_17
  - libgfortran4=7.5.0=ha8ba4b0_17
  - libgomp=9.3.0=h5101ec6_17
  - libprotobuf=3.17.2=h4ff587b_1
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - markdown=3.3.4=py37h06a4308_0
  - mkl=2021.3.0=h06a4308_520
  - mkl-service=2.4.0=py37h7f8727e_0
  - mkl_fft=1.3.0=py37h42c9631_2
  - mkl_random=1.2.2=py37h51133e4_0
  - multidict=5.1.0=py37h27cfd23_2
  - ncurses=6.2=he6710b0_1
  - numpy=1.20.3=py37hf144106_0
  - numpy-base=1.20.3=py37h74d4b33_0
  - oauthlib=3.1.1=pyhd3eb1b0_0
  - openssl=1.1.1k=h27cfd23_0
  - opt_einsum=3.3.0=pyhd3eb1b0_1
  - pip=21.1.3=py37h06a4308_0
  - protobuf=3.17.2=py37h295c915_0
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.8=py_0
  - pycparser=2.20=py_2
  - pyjwt=2.1.0=py37h06a4308_0
  - pyopenssl=20.0.1=pyhd3eb1b0_1
  - pysocks=1.7.1=py37_1
  - python=3.7.10=h12debd9_4
  - python-flatbuffers=1.12=pyhd3eb1b0_0
  - readline=8.1=h27cfd23_0
  - requests=2.25.1=pyhd3eb1b0_0
  - requests-oauthlib=1.3.0=py_0
  - rsa=4.7.2=pyhd3eb1b0_1
  - scipy=1.6.2=py37had2a1c9_1
  - setuptools=52.0.0=py37h06a4308_0
  - six=1.16.0=pyhd3eb1b0_0
  - sqlite=3.36.0=hc218d9a_0
  - tensorboard=2.5.0=py_0
  - tensorboard-plugin-wit=1.6.0=py_0
  - tensorflow=2.4.1=gpu_py37ha2e99fa_0
  - tensorflow-base=2.4.1=gpu_py37h29c2da4_0
  - tensorflow-estimator=2.5.0=pyh7b7c402_0
  - tensorflow-gpu=2.4.1=h30adc30_0
  - termcolor=1.1.0=py37h06a4308_1
  - tk=8.6.10=hbc83047_0
  - typing-extensions=3.10.0.0=hd3eb1b0_0
  - typing_extensions=3.10.0.0=pyh06a4308_0
  - urllib3=1.26.6=pyhd3eb1b0_1
  - werkzeug=1.0.1=pyhd3eb1b0_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - wrapt=1.12.1=py37h7b6447c_1
  - xz=5.2.5=h7b6447c_0
  - yarl=1.6.3=py37h27cfd23_0
  - zipp=3.5.0=pyhd3eb1b0_0
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - opencv-python==4.5.3.56
    - pyaml==20.4.0
    - pyyaml==5.4.1
    - tensorflow-addons==0.13.0
    - typeguard==2.12.1
