GPU_ID: '0' 
model_restore: 'exp/logs/bmx-trees/checkpoint_50000' 

test_dir: exp/results/bmx-trees
dir_video: 'inputs/videos/bmx-trees' 
dir_mask: 'inputs/masks/bmx-trees'


img_shapes: [320, 600]
coarse_only: False 
use_refine: True 
padding: 'SAME'
